name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install typst from crates.io
      uses: baptiste0928/cargo-install@v3
      with:
        crate: typst-cli

    - name: Make pdf
      run: make

